### ISSUE TITLE
Mistake in date conversion

### ISSUE THREAD

**Issue by jebraili** [mohamedsabil83/laravel-hijrian#1]
hi thanks for your code
problem with some date, for examle test Hijrian::hijri('2019/10/28')
this return 1441-03-01 that it is wrong, but 1441-02-29  is true

**Comment by mohamedsabil83** [comment]
Hi, Thank you for noticing that. It's rare to get a wrong date as it's calculated according to the UmAlquraa calendar.
I'll review it. also, any PRs are welcome.
